rformassspectrometry/Spectra

- R/functions-util.R
- tests/testthat/test_functions-util.R
While thinking about the `.rbind_fill` implementation I found that the old one just works with `SimpleList` or `NumericList` if it is present in the first `DataFrame` (given as first argument).
```r
library("S4Vectors")
library("microbenchmark")
.rbind_fill <- function(...) {
dots <- list(...)
cols_class <- lapply(dots, function(z) {
if (is.matrix(z)) {
res <- rep(class(z[, 1]), ncol(z))
names(res) <- colnames(z)
}
else res <- vapply(z, class, character(1))
res
})
cols_class <- unlist(cols_class)
cols_names <- unique(names(cols_class))
cols_class <- cols_class[cols_names]
res <- lapply(dots, function(z) {
cnz <- colnames(z)
rnz <- nrow(z)
is_matrix <- is.matrix(z)
mis_col <- setdiff(cols_names, cnz)
for (mc in mis_col) {
mc_class <- cols_class[mc]
if (mc_class == "factor")
z <- cbind(z, …
```
> .rbind_fill doesn't work if the first DataFrame doesn't contain a SimpleList but the second one

- R/MsBackendMzR-functions.R
- R/Spectra-functions.R
- R/Spectra.R
- man/MsBackend.Rd
- man/Spectra.Rd
- `mz,Spectra` and `intensity,Spectra` avoid parallel processing. This significantly improves performance on in memory backends (issue #44).
- Avoid import of core spectra variables with only `NA` in `MsBackendMzR` (issue #67).
> refactor: changes addressing performance bottlenecks

- DESCRIPTION
- R/MsBackendMzR.R
- This fixes issue #82 by using `rbindFill` instead of `rbind` in combining the
header of the individual mzML files into the final `DataFrame`.
- Note that this will also require `MsCoreUtils` 1.1.4 that fixes an issue in `rbindFill` if only a single `DataFrame` is passed.
> fix: support import of mzML files with different header columns

- DESCRIPTION
- NEWS.md
- R/Spectra.R
- R/peaks-functions.R
- man/Spectra.Rd
- tests/testthat/test_Spectra.R
- tests/testthat/test_peaks-functions.R
- vignettes/Spectra.Rmd
- `filterIntensity` supports a function with parameter `intensity` that allows to perform a peak intensity-based filtering (e.g. remove peaks that have an intensity smaller than 30% of the largest intensity in that spectrum).
> Add support for user-provided function in filterIntensity

- DESCRIPTION
- NEWS.md
- R/MsBackend.R
- R/peaks-functions.R
- man/MsBackend.Rd
- tests/testthat/test_MsBackendDataFrame.R
- tests/testthat/test_MsBackendHdf5Peaks.R
- tests/testthat/test_MsBackendMzR.R
- tests/testthat/test_Spectra.R
- Fix `dropNaSpectraVariables` does no longer drop the `"mz"` and `"intensity"`
columns (issue #138).
- Update also documentation of `spectraData,MsBackend` to clearly state it has
to return also m/z and intensity values.
> fix: dropNaSpectraVariables no longer drops mz and intensity

- DESCRIPTION
- NEWS.md
- R/Spectra.R
- Fix that the backend is changed even if the backend passed with `source`
extends the backend specified with `backend` (issue #146).
> fix: ensure backend is changed in Spectra,character constructor

- DESCRIPTION
- NEWS.md
- R/Spectra.R
- man/Spectra.Rd
- tests/testthat/test_Spectra.R
Implement a `Spectra,ANY` constructor method that *imports* data using the `source` backend (eventually converting to `backend` backend). This supports also to create a `Spectra` object based on a e.g. database connection, given that the `MsBackend` specified with `source` knows how to handle that (issue #152).
I think this will save us from unnecessary additional implementation of constructor methods, e.g. for `Spectra,DBIconnection` or similar.
> refactor: replace Spectra,DataFrame by Spectra,ANY

- .github/workflows/check-bioc.yml
- NEWS.md
- R/Spectra.R
- R/peaks-functions.R
- man/Spectra.Rd
- tests/testthat/test_MsBackendDataFrame.R
- tests/testthat/test_Spectra.R
- tests/testthat/test_peaks-functions.R
This PR mainly adds support for passing arguments to the filter function of `filterIntensity` (issue #164).
> Add support for arbitrary parameters in filterIntensity (issue #164)

- DESCRIPTION
- NEWS.md
- R/MsBackend.R
- R/Spectra.R
- man/MsBackend.Rd
- man/Spectra.Rd
- tests/testthat/test_Spectra.R
- Add parameter `f = dataOrigin(object)` to `filterPrecursorScan` to allow
filtering within each sample/file. This fixes issue #194.
> fix: per-file filtering in filterPrecursorScan (issue #194)

- DESCRIPTION
- NEWS.md
- R/Spectra.R
- R/peaks-functions.R
- man/Spectra.Rd
- tests/testthat/test_Spectra.R
- tests/testthat/test_peaks-functions.R
- vignettes/Spectra.Rmd
- Add parameter `remove` to `filterMzValues` to allow removing instead of
keeping matching peaks.
> feat: filterMzValues supports removing peaks (issue #209)

- DESCRIPTION
- NEWS.md
- R/MsBackendMzR-functions.R
- R/MsBackendMzR.R
- R/zzz.R
- tests/testthat/test_MsBackendMzR-functions.R
- This adds a fix from MSnbase to address random errors retrieving peak data
from mzML files using the `MsBackendMzR` backend on macOS (issue #212 )
> fix: fix random errors with MsBackendMzR on macOS

- NEWS.md
- R/Spectra-functions.R
- R/Spectra.R
- man/Spectra.Rd
- tests/testthat/test_Spectra-functions.R
The `joinSpectraData(x, y, by.x, by.y)` function now checks for duplicates in the x and y keys. 
- If there's duplicates in the `Spectra` key (i.e. in `x[[by.x]]`), then an error is thrown. Indeed, this key should be unique and the user would need to sort this out it it wasn't. 
- If there's duplicates in the `y` key (i.e. in `y[[by.y]]`), then a warning is thrown, and the last occurrences of the duplicated entries are used (as as result of using `match()`). The documentation provides guidance how to manage this.
> features: joinSpectraData() checks for key duplicates

- .github/workflows/check-bioc.yml
- DESCRIPTION
- NEWS.md
- R/Spectra.R
- R/peaks-functions.R
- man/Spectra.Rd
- man/hidden_aliases.Rd
- tests/testthat/test_Spectra.R
- tests/testthat/test_peaks-functions.R
- vignettes/Spectra.Rmd
- Expand documentation and vignette on the usage of the `bin,Spectra` method.
- `bin,Spectra` gains also parameter `FUN` to enable specifying the aggregation
function.
> docs: expand examples and description on bin

- DESCRIPTION
- NEWS.md
- R/MsBackendMzR-functions.R
- R/Spectra.R
- tests/testthat/test_MsBackendMzR.R
- Fix error extracting spectra data from an `MsBackendMzR` of length 0.
> fix: MsBackendMzR of lenght 0

- DESCRIPTION
- NEWS.md
- R/MsBackendMemory-functions.R
- R/MsBackendMemory.R
- R/Spectra.R
- man/Spectra.Rd
- tests/testthat/test_MsBackendMemory.R
- vignettes/MsBackend.Rmd
- Fix `selectSpectraVariables,MsBackendMemory`: return values for *core* spectra variables `"mz"` and `"intensity"` even if they are not in peaks data.
> fix: selectSpectraVariables,MsBackendMemory

- DESCRIPTION
- NEWS.md
- vignettes/Spectra.Rmd
Add an additional example for a spectra processing method helpful for matching fragment spectra against reference libraries.
> docs: add example for spectra processing (remove precursor peaks)

- R/fft_spectrum.R
the filepath in the example is no longer valid
> updated filepath in filterFourierTransformArtefacts example

- .Rbuildignore
- DESCRIPTION
- NEWS.md
- R/MsBackendMzR.R
- R/Spectra.R
- tests/testthat/test_Spectra.R
Update the `Spectra()` constructor method to better support initialization with backends defining their own specific parameters. This also fixes https://github.com/rformassspectrometry/MsBackendMetaboLights/issues/4
> Improve and fix the Spectra constructor method

- .github/workflows/check-bioc.yml
- DESCRIPTION
- NEWS.md
- R/Spectra.R
- man/spectraData.Rd
- tests/testthat/test_Spectra.R
This PR adds a new parameter `return.type` to `peaksData()`. With `return.type = "list"` the data would not be converted first to a `SimpleList` which has performance advantages (avoids copying of the data, but also operations such as `split()` etc are faster on a `list` than on a `SimpleList`). Thus, we might set `return.type = "list"` in other packages such as *xcms*.
> feat: add parameter return.type to peaksData

- DESCRIPTION
- NEWS.md
- R/MsBackend.R
- R/Spectra.R
- inst/test_backends/test_MsBackend/test_spectra_subsetting.R
- man/MsBackend.Rd
- man/filterMsLevel.Rd
- tests/testthat/test_MsBackendMemory.R
- vignettes/MsBackend.Rmd
- Applying the retention time filter of `filterRt()` to **all** spectra when `msLevel. = integer()` is used.
> refactor: filterRt to support msLevel. = integer()

- DESCRIPTION
- NEWS.md
- R/Spectra.R
- man/Spectra.Rd
The parallelization should work better now ! 
Also removed it in a function definition as it was not and could not be passed down.
> fix `BPPARAM` parameter passing in `peaksData()`
